### PR TITLE
i18n(zh-cn): Update configuration.mdx & Update sidebar.mdx

### PR DESCRIPTION
**Pull request by liruifengv**
#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- Update configuration.mdx
- Update sidebar.mdx
- Use zh-CN as example in Chinese docs

### CODE REVIEW

**Review by HiDeoo — COMMENTED** [review]
Thanks for the translation 🙌 

I think this may be missing the changes from https://github.com/withastro/starlight/pull/881 which uses a BCP-47 language tag with a regional subtag for the "Translating labels" section example.

**Comment by liruifengv** [comment]
> Thanks for the translation 🙌
> 
> I think this may be missing the changes from #881 which uses a BCP-47 language tag with a regional subtag for the "Translating labels" section example.

Yeah. I saw it. Thank you.

**Comment by liruifengv** [comment]
I updated it. And Use zh-CN as example in Chinese docs. @HiDeoo

**Review by delucis — APPROVED** [review]
Thanks for the update @liruifengv! 🙌

**Pull request merged**
