### PR TITLE
i18n(de): translate components/cards

### PR DESCRIPTION
**Pull request by trueberryless**
#### Description

Translation of `components/cards.mdx` into German language.

### CODE REVIEW

**Comment by trueberryless** [comment]
Waiting for icon reference cause broken links...

**Comment by trueberryless** [comment]
Link fixed in https://github.com/withastro/starlight/pull/2460

**Comment by trueberryless** [comment]
Link fixed in https://github.com/withastro/starlight/pull/2454

**Review by HiDeoo — APPROVED** [review]
Thanks for another update :star2:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and this looks great to me!

**Pull request merged**
