### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by isturiz**
Update copyright year

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

### CODE REVIEW

**Comment by liruifengv** [comment]
Maybe we can write like `2023–present`?

**Comment by jacobdalamb** [comment]
License isn't something that's supposed to be updated.

**Comment by isturiz** [comment]
> License isn't something that's supposed to be updated.

Uh, I didn't know, I thought it was updated like the footer of the page that is usually kept updated with respect to the current year.

**Comment by jacobdalamb** [comment]
> > License isn't something that's supposed to be updated.
> 
> Uh, I didn't know, I thought it was updated like the footer of the page that is usually kept updated with respect to the current year.

It's okay. I didn't know this until recently. Updating the year in a website's footer communicates the activity and current relevance of the site, assuring visitors that it's well-maintained. As for a license, the year typically indicates when it was implemented, often coinciding with the project's creation date.

**Comment by isturiz** [comment]
> > > License isn't something that's supposed to be updated.
> 
> > 
> 
> > Uh, I didn't know, I thought it was updated like the footer of the page that is usually kept updated with respect to the current year.
> 
> 
> 
> It's okay. I didn't know this until recently. Updating the year in a website's footer communicates the activity and current relevance of the site, assuring visitors that it's well-maintained. As for a license, the year typically indicates when it was implemented, often coinciding with the project's creation date.

Yes, I was researching and found exactly what you mentioned. Thank you very much, learned something new. ✅

**Pull request closed without merging**
