### PR TITLE
Add `z-index` to mobile table of contents.

### PR DESCRIPTION
**Pull request by chopfitzroy**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

- What does this PR change? Give us a brief description.
  - Adds `z-index` to mobile table of contents so content can't scroll over the top of it.

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for this PR! Could you share an example site where this is an issue currently?

**Comment by chopfitzroy** [comment]
Heya, not a published site (yet) but I was getting this issue last night when using a [Sandpack](https://sandpack.codesandbox.io/) component.

Video attached.

https://github.com/withastro/starlight/assets/2978850/6817a4e8-2e11-45b6-8c4f-e122644ccf18

**Review by delucis — APPROVED** [review]
Hey @chopfitzroy — sorry for the wait on this one!

I just cleaned it up to move the `z-index` value to a custom property alongside our other values and isolate the main page content in its own stacking context, so even if user content has really high `z-index` values, it will still be below Starlight’s header UI.

Thanks again for the report and the PR! Will get this out in our next patch release.

**Comment by chopfitzroy** [comment]
Love it! Please let me know if you need anything else from me!

**Comment by delucis** [comment]
Nope, we’re good to go! Will get this out tomorrow.

**Pull request merged**
