### PR TITLE
feat: multiple sidebars support

### LINKED ISSUE #658: Feature Request: Multiple Sidebar Support
### What version of `starlight` are you using?

0.9.0

### What is your idea?

Add the support of multiple sidebar instances for better navigation.

Similar feature to what [docusaurus](https://docusaurus.io/docs/sidebar/multiple-sidebars) currently provides, which basically allows you to assign specific sidebars to specific routes/endpoints and/or documents of your site.

## Frontmatter (concept)
```md
---
title: About this project
sidebar:
  group: <sidebarInstance>
---
```

In your astro config you'd then define the sidebars like the way you did before but you add some kind of name/Identifier to it.

### Why is this feature necessary?

Would be basically a QoL change which would allow users to structure their documentation better. 

As Starlight (as of this date) doesn't have a navbar where users are able to freely navigate between routes it wouldn't be the most ideal thing to add (**as of now**) in my opinion.

### Do you have examples of this feature in other projects?

- [Docusaurus](https://docusaurus.io/docs/sidebar/multiple-sidebars)
- [VuePress](https://vuepress.vuejs.org/theme/default-theme-config.html#multiple-sidebars)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by scarf005**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

https://github.com/withastro/starlight/assets/54838975/e16728a6-b107-4f8c-953f-4dc2d3802ddf

- Closes #658 
- Made `sidebar` configuration can be a record of sidebars with links to match from.
- Copied a new example page, `examples/navbars` to demonstrate new navbar support.

#### TODO

- [ ] Update docs
- [ ] Add E2E tests
- [ ] handle base path

#### Help Needed

- would there be a better way to make navbars more responsive?
- header column width changes w/wo sidebars, but i was unable to find correct CSS equation to resolve the issue.

| Without sidebar | With sidebar |
|--------|--------|
| ![no-sidebar][no-sidebar] | ![sidebar][sidebar] |

[no-sidebar]: https://github.com/withastro/starlight/assets/54838975/60cf6e27-19cd-4c95-8560-4162519db131
[sidebar]: https://github.com/withastro/starlight/assets/54838975/dd77965a-a714-4974-a6ac-81864ea4fec6

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for trying to tackle this @scarf005! There’s a lot of considerations going into how to implement a feature that has as a big an impact as this one. It might be best to spend some time discussing what an API should look like and all the ways it interacts with different parts of how Starlight works to make sure we understand all the use cases and implications.

I’d suggest we discuss in #658 first, before looking at implementing anything, so that we don’t risk sinking too much time into building code that might not end up being the solution we go for. Still appreciate you trying to figure this out though!

**Comment by scarf005** [comment]
I see, thanks for the consideration. opening it as it's mostly 'feature complete' and could spark some ideas.

**Comment by delucis** [comment]
Closing as it is now somewhat stale and our [component overrides](https://starlight.astro.build/guides/overriding-components/) system offers some workarounds while we figure out the bigger picture. Thanks again for the PR!

**Comment by asturur** [comment]
Do you have any example on how the component ovverides let me achieve multiple sidebars?

**Comment by delucis** [comment]
@asturur Here’s one example of using the URL of the current page to filter the sidebar for different products: https://stackblitz.com/edit/github-dubgkv?file=src%2Foverrides%2FSidebar.astro

**Comment by p-dg** [comment]
@asturur Thanks for your example. I am a designer playing around with starlight, trying to implement customized sidebars per route. Your example helps, but Pagination and your styling example only work on the first level ob the subdirectory.
So styling for product-2 and Pagination works on
`/product-2/[index]` but not on succeeding pages, for example
`/product-2/set-up`
Can you provide a working example for subpages / subdirectories? Thanks in advance?

**Comment by carcigenicate** [comment]
@delucis 

I figured it out in case you're still interesting. All you need to do is change the definition of `currentBase`:

```javascript
const currentBase = `/${Astro.url.pathname.split('/')[1]}`;
```

Now, it only considers the first segment in the path.

**Comment by carcigenicate** [comment]
@delucis 

I figured it out in case you're still interested. All you need to do is change the definition of `currentBase`:

```javascript
const currentBase = `/${Astro.url.pathname.split('/')[1]}`;
```

Now, it only considers the first segment in the path.

**Pull request closed without merging**
