### PR TITLE
i18n(de): translate components/code

### PR DESCRIPTION
**Pull request by trueberryless**
#### Description

Translation of `components/code.mdx` into German language.

### CODE REVIEW

**Comment by trueberryless** [comment]
Link fixed in #2458

**Review by HiDeoo — COMMENTED** [review]
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://contribute.docs.astro.build/reviewers/reviewing-translations/) and everything looks good to me 👍 This PR should be mergeable once links validation passes.

**Comment by trueberryless** [comment]
Thanks for the review!

**Review by HiDeoo — APPROVED** [review]
Another great translation ready to be merged, thanks for your contribution :rocket:

**Pull request merged**
