### PR TITLE
i18n(es): Update `authoring-content`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### Description

- What does this PR change? Give us a brief description.
Updated `authoring-content` based on these commits 9ed034b0e7131e11620a6b1c537bb3c0fdd258d0 & c0070782d1e5a4bcef831abb0aaa5c5840cd67f3

### CODE REVIEW

**Review by HiDeoo — APPROVED** [review]
Thanks for the translation :raised_hands:

As a non-native speaker, I reviewed this PR using the [Docs Translation Review Checklist](https://hackmd.io/1KYnrpUQR0SAGTzHIUoUDg?view) and this looks good to me 👍

**Review by Waxer59 — APPROVED** [review]
LGTM ✅

**Comment by dreyfus92** [comment]
Thank you so much for your reviews @Waxer59 and @HiDeoo 😁

**Comment by kevinzunigacuellar** [comment]
Los Gatos Toman Leche!

**Review by delucis — APPROVED** [review]
We need more PRs to test Kevin’s acronym skills 😸 

Thanks for the update and reviews everyone!

**Pull request merged**
