### PR TITLE
Refactor `<Steps>` counter

### LINKED ISSUE #2032: `<Steps>` Numbers out of order
In Chrome 126 there was a change to CSS counters that has changed the way the `<Steps>` component renders.

There are a number of options for how to handle this. This issue is meant to serve as tracking of this. 

Here is the [minimal reproduction](https://codepen.io/delucis/details/wvbyGVJ) of the issue on codepen

This bug can be seen [here](https://starlight.astro.build/guides/css-and-tailwind/#add-tailwind-to-an-existing-project)
## Resources

**Here are the relevant Chromium issues/commits:**
- [Bug report of 126](https://issues.chromium.org/issues/346974104)
- [Original issue that proposed the changes to Chromium](https://issues.chromium.org/issues/40638899)
  - @delucis 's [comment on the original issue](https://issues.chromium.org/issues/40638899#comment44)
- [Merged commit to chromium attempting to fix](https://chromium-review.googlesource.com/c/chromium/src/+/5630408) 

**Here is history of how starlight attempted to handle this so far:**
- [ Attempt 1 ](https://github.com/withastro/starlight/pull/1948) which was [reverted](https://github.com/withastro/starlight/pull/1955) due to creating other problems

## Some relevant comments open for discussion:

> And we might also look at some temporary mitigation, annoying though that is — in theory we could dive into rehype or something to hard code the markers instead of using ::before and CSS counters, but obviously would love to avoid that if possible. - @delucis 

## Next steps:

1. Test fixes in Canary chromium 
2. Identify when next stable version (with the fix) will be released 
3. Decide if starlight should take action at all 
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by HiDeoo**
#### Description

- Closes #2032

A new attempt at fixing `<Steps>` counter using a custom counter.

This PR is a draft as I just wanted a preview URL to share. If the approach is working and accepted, tests would need to be updated and a changeset to be added.

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
I think this looks good!

Tested in Chrome 126, Safari, and Firefox on macOS without issues. Maybe worth testing on Windows if someone is able? I think we had issues with Windows on the previous fix.

**Comment by lorenzolewis** [comment]
Tested on Safari on iOS 17.5.1 (21F90) and LGTM!

**Comment by liruifengv** [comment]
Tested in Chrome, Edge and Firefox on Windows11, works perfect!

**Comment by delucis** [comment]
Thanks for testing @lorenzolewis and @liruifengv! I know @HiDeoo may have less time to work on this and I feel like the bug is relatively urgent, so will take over this PR now and polish it up for release.

**Review by delucis — APPROVED** [review]
Thanks again for figuring out this fix @HiDeoo!

**Pull request merged**
