### PR TITLE
add Open SaaS card 

### PR DESCRIPTION
**Pull request by vincanger**
#### Description

added a card for OpenSaaS.sh docs to the Starlight showcase

### CODE REVIEW

**Review by HiDeoo — COMMENTED** [review]
Thanks for your contribution, great submission :raised_hands:

At the moment, the build is failing due to the showcase entry requiring an image and we do not support remote images. The image should be a screenshot of the homepage of your Starlight project, located in the `docs/src/assets/showcase` directory, named after the entry `href` URL and be 800x450px in size. Would you be okay with adding this to your PR? If needed, this [pull request](https://github.com/withastro/starlight/pull/1269/files) can be used as a reference.

A few extra notes:

- I wonder if it would make more sense for the URL to be https://docs.opensaas.sh
- The new entry should be at the bottom of the list, not the top

**Comment by delucis** [comment]
Hey @vincanger! Are you still interested in getting this added?

**Comment by delucis** [comment]
Hey @vincanger happy to reopen this when you have a moment, but closing for now while tidying up our open PRs — thanks again for opening 🙌

**Comment by vincanger** [comment]
> Hey @vincanger happy to reopen this when you have a moment, but closing for now while tidying up our open PRs — thanks again for opening 🙌

hey sorry for the delayed response @delucis -- i created a new PR with the requested changes here https://github.com/withastro/starlight/pull/1359

**Pull request closed without merging**
