### PR TITLE
Improve social icons accessibility

### PR DESCRIPTION
**Pull request by natemoo-re**
#### Description

- Updates `<SocialIcon />` styling for improved accessibility.
- Specifically, the component now meets the [Target Size (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html) success criteria defined by [Web Content Accessibility Guidelines (WCAG) 2.2](https://www.w3.org/TR/WCAG22/).
- In plan terms, the bounding box of the `<a>` was a 16px square. Now it is appropriately sized as a 32px square.

**Before**
A 16px bounding box over the Discord logo

**After**
A 32px bounding box over the GitHub logo

### CODE REVIEW

**Comment by kevinzunigacuellar** [comment]
LGTM!

**Review by HiDeoo — APPROVED** [review]
Love the change, great improvement and this also brings them on par with the mobile search icon and mobile menu icon :thumbsup: (and I guess the AAA level would look a bit weird for these icons as this would require some extra spacing between the icons)

**Review by ElianCodes — APPROVED** [review]
Great work Nate! Looking fine 👌

**Review by delucis — APPROVED** [review]
Lovely work @natemoo-re! Thank you for spotting this and prioritising it 💖

**Pull request merged**
