### PR TITLE
Add `starlight-view-modes` to plugin integrations list

### PR DESCRIPTION
**Pull request by trueberryless**
Adding the Plugin `starlight-view-modes` to plugin site...

### CODE REVIEW

**Review by delucis — APPROVED** [review]
Thank you for adding this @trueberryless!

**Comment by trueberryless** [comment]
> ## Lunaria Status Overview
> 🌕 **This pull request will trigger status changes.**
> 
> Learn more
> ### Tracked Files
> Locale	File	Note
> fr	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Ffr%2Fresources%2Fplugins.mdx)	Localization changed, will be marked as complete.
> ko	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Fko%2Fresources%2Fplugins.mdx)	Localization changed, will be marked as complete.
> pt-pt	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Fpt-pt%2Fresources%2Fplugins.mdx)	Localization changed, will be marked as complete.
> en	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Fresources%2Fplugins.mdx)	Source changed, localizations will be marked as outdated.
> ru	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Fru%2Fresources%2Fplugins.mdx)	Localization changed, will be marked as complete.
> zh-cn	[resources/plugins.mdx](https://github.com/withastro/starlight/blob/2e7f1cc93c45b29e8d1a3b708654060c63328ac3/docs%2Fsrc%2Fcontent%2Fdocs%2Fzh-cn%2Fresources%2Fplugins.mdx)	Localization changed, will be marked as complete.
> Warnings reference

Will the localizations be marked as outdated or completed? Because idk if the en localization will trigger first and afterwards the others will trigger the completion again or vice versa (all translations trigger completion but en overrides afterwards to outdated...) Let's hope for the first option xD

**Review by delucis — COMMENTED** [review]
> Will the localizations be marked as outdated or completed?

Ah, we should only change the English page in this PR please.

Our workflow is like this:

1. Someone updates docs content in English
2. Native speakers of each of our supported languages submit PRs to update their language to match the English

This allows us to avoid mixing new content reviews and translation reviews (which are quite different focuses), lets us merge English changes quickly without waiting for translations, and also makes sure we leave translations to our experts for each language.

**Comment by trueberryless** [comment]
Okay, my bad! Is it okay, when I remove the translations here and make new PRs for the translations because the text is not that much and I don't want to bother the translators with such small updates...

**Comment by delucis** [comment]
> Is it okay, when I remove the translations here and make new PRs for the translations because the text is not that much and I don't want to bother the translators with such small updates...

We really only encourage translation PRs from people who know the languages well (automated translations often include unidiomatic phrasing that I am not in a position to review for languages I don’t speak). So you’re welcome to submit translation PRs for languages you speak, but not for any you don’t.

In any case, you definitely don’t need to feel bad about bothering the translators — people will get to the updates when they have time, and often small updates may even be _nicer_ for them, because those are contributions they can do quickly when they have a few moments of spare time.

**Comment by trueberryless** [comment]
Okay, thank you for the encouraging words!

**Review by delucis — APPROVED** [review]
Thanks again for working on the plugin and sharing it here @trueberryless! 🚀 

I checked it out and it’s cool to see that focused view working.

(By the way, I removed the changeset too, because we only need that for changes to the core Starlight package, not also for docs changes.)

**Comment by trueberryless** [comment]
Perfect! Thank you for clarifying the changeset as well, i didn't know that!

**Pull request merged**
