### PR TITLE
fixes issue #674

### PR DESCRIPTION
**Pull request by vedmalex**
this PR fixes issue with pagefind configuration #674

### CODE REVIEW

**Comment by vedmalex** [comment]
@HiDeoo I've fixed deps and will examine search changes

**Comment by bglw** [comment]
Hey @HiDeoo & @vedmalex 👋 

Just popping into this PR to mention that Pagefind `v1.0.0-beta.3` includes improvements around compound words and excerpts, thanks for the feedback! ❤️ 

That excerpt _does_ have a lot of mentions of `component`, so it might still favor the code, but in most cases compound words will be less likely to be the focus of an excerpt.

Additionally, `beta.3` adds the ability to lower the weight of sections, and this weighting is used for both search ranking and excerpt generation, which means you can tailor this further by wrapping your code blocks in `data-pagefind-weight="0.5"` (or any number between 0 and 1) — which would make code even less likely to be the focus.

**Comment by HiDeoo** [comment]
Damn @bglw, this looks super great and this was so fast 😮 Thanks for the amazing work! Time to play with all the new changes ^^

**Comment by bglw** [comment]
Follow-up to ☝️ 

There was a wee issue with that initial fix that meant some compound words actually ranked _higher_ 😅 

That's fixed on `v1.0.0-beta.5`, if you want to try it out in the next... 22 hours or so 😄

**Comment by bglw** [comment]
Final follow-up, `v1.0.0-beta.6` sneaks in some last minute quick-wins on ranking.

Before / after:
Pagefind MDN Search Demo

**Comment by HiDeoo** [comment]
> Final follow-up, `v1.0.0-beta.6` sneaks in some last minute quick-wins on ranking.

Wow, this looks super neat! I have to say that I am super impatient, amazing work once again.

**Pull request merged**
