### PR TITLE
fix: Better alignment of selected option within select box.

### LINKED ISSUE #1552: Select options are not centrally aligned
### What version of `starlight` are you using?

0.19.1

### What version of `astro` are you using?

4.4.4

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the Bug

This is how they look

image

They should look like that

image
---

Same with the language selection box

image
image

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rgilsimoes**
#### Description

- Closes #1552
- Improves selected option alignment on select component.

### CODE REVIEW

**Review by at-the-vr — COMMENTED** [review]
I think its the position (left/right) of Icons that needs to be fixed wrt the Issue linked that is to centrally align items inside the label

**Comment by rgilsimoes** [comment]
That was the issue request but my suggestion was just to adjust the icon placement. @delucis was ok with this approach as well.

**Review by delucis — COMMENTED** [review]
Thanks for tackling this @rgilsimoes! And for your patience waiting on a review.

I noticed this changes the overall spacing of the components, not only the outline positioning:

#### Before

image

#### After

image

Basically now there is more spacing to the left of the menus, causing unbalanced spacing around the vertical line for example.

I think we should aim to match the current layout and only move the outline. Do you think you could tackle that?

**Comment by rgilsimoes** [comment]
> I think we should aim to match the current layout and only move the outline. Do you think you could tackle that?

That will cause the outline of the ThemeSelector to be very close to the vertical line. Is that intended?

I think the outline is the point of reference to space the elements evenly:

image

**Comment by delucis** [comment]
> I think the outline is the point of reference to space the elements evenly:

Yes, I think that’s fine! I think the outline is understood as an overlay on the layout, and is not visible most of the time, so we should optimize the layout for the most common display style (i.e. when the outline is not visible).

**Comment by evadecker** [comment]
@rgilsimoes Are you planning to continue this PR? This alignment has been bugging me too 😅

Happy to contribute to this PR or create a new branch!

**Comment by delucis** [comment]
@evadecker Would love the contribution! Feel free to make suggestions on this PR if that’s enough to fix it, or open a new one. Thank you 💖

**Comment by evadecker** [comment]
> @evadecker Would love the contribution! Feel free to make suggestions on this PR if that’s enough to fix it, or open a new one. Thank you 💖

PR up: https://github.com/withastro/starlight/pull/2062

**Comment by rgilsimoes** [comment]
Sorry for the late reply! Schedule has been tight! Thank's for continuing @evadecker !

**Pull request closed without merging**
