### PR TITLE
i18n(es): Update `i18n.mdx`

### PR DESCRIPTION
**Pull request by K1ri86**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- Changes or translations of Starlight docs site content

#### Description
- What does this PR change?
- Update `i18n.mdx` #809

#### Hacktoberfest
- I am participating in the Hacktoberfest!

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Hi @K1ri86 thanks for your PR! We actually don’t want to translate the values of this object. As it says just before the code snippet:

> Estos son los valores predeterminados en inglés de las cadenas existentes que se incluyen en Starlight:

“en inglés”, so we should keep them in English!

I think that means the only change needed is to add the `404.text` line (in English)?

**Comment by K1ri86** [comment]
> Hi @K1ri86 thanks for your PR! We actually don’t want to translate the values of this object. As it says just before the code snippet:
> 
> > Estos son los valores predeterminados en inglés de las cadenas existentes que se incluyen en Starlight:
> 
> “en inglés”, so we should keep them in English!
> 
> I think that means the only change needed is to add the `404.text` line (in English)?

I saw it translated into other languages and thought it was necessary, so I reverted the commit and added the necessary changes.

**Review by delucis — APPROVED** [review]
Perfect — thank you @K1ri86! And sorry for the extra work you had to do for those translations that weren’t needed 😁

**Comment by K1ri86** [comment]
> Perfect — thank you @K1ri86! And sorry for the extra work you had to do for those translations that weren’t needed 😁

@delucis You can accept hacktoberfest ? 😁

**Comment by delucis** [comment]
Done! Sorry I missed that.

**Pull request merged**
