### PR TITLE
Improvements to Arabic translation UI

### PR DESCRIPTION
**Pull request by jermanuts**
#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

Improvements and changed some transliteration.

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Thank you for the PR @jermanuts! Would love someone who speaks Arabic to review these changes if possible.

In the meantime, would you mind giving a quick description of what was needed here and why? For example, explaining why `داكن` is preferable to `ليلي`, etc.

**Comment by X7md** [comment]
> Thank you for the PR @jermanuts! Would love someone who speaks Arabic to review these changes if possible.
> 
> In the meantime, would you mind giving a quick description of what was needed here and why? For example, explaining why `داكن` is preferable to `ليلي`, etc.

In Standard Arabic mostly you will see "داكن".

iOS:
image

**Comment by delucis** [comment]
Thanks for the input @X7md! Can you confirm the rest of the changes look good to you?

**Comment by X7md** [comment]
Also google

IMG_3274

IMG_3273

**Comment by delucis** [comment]
Great! How about the other changes — https://github.com/withastro/starlight/pull/778/files ?
This PR changes a bunch, not just `داكن`.

**Comment by jermanuts** [comment]
> Great! How about the other changes — https://github.com/withastro/starlight/pull/778/files ? This PR changes a bunch, not just `داكن`.

You can check here https://mostalah.org/ type any word in english. Arabeyes are the best.

**Review by delucis — APPROVED** [review]
Thanks for the contribution @jermanuts! Using machine translation, the changes seem OK (although the existing text also looks fine that way, so it’s a bit hard for me to judge if the changes are needed or not). Happy to include these though and hopefully people will let us know if they’re unhappy with any of these updates.

**Pull request merged**
