### PR TITLE
Update Lunaria to latest

### PR DESCRIPTION
**Pull request by yanthomasdev**
#### Description

This PR updates Lunaria to `v0.1.1` which is important since it fixes a nasty regression in how we link to GitHub's source history.

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Is there any way to re-run the size report? It's curious that it jumped up so high for something that I don't believe should impact it.

**Comment by yanthomasdev** [comment]
> Is there any way to re-run the size report? It's curious that it jumped up so high for something that I don't believe should impact it.

For some reason, it seems pnpm updated all dependencies when I updated Lunaria 😅, should be good now

**Review by liruifengv — APPROVED** [review]
LGTM! ✨

**Review by delucis — APPROVED** [review]
Thanks @yanthomasdev! And @lorenzolewis and @liruifengv for reviewing 💖

**Pull request merged**
