### PR TITLE
Add new starlight-ghostcms to Community plugins list

### PR DESCRIPTION
**Pull request by Adammatthiesen**
#### Description

Add new starlight-ghostcms to Community plugins list.

starlight-ghostcms

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Yay! Thanks @Adammatthiesen — exciting to see this released.

I think this should actually go in the “Community plugins” section instead of the “tools and integrations” section given this is actually a Starlight plugin by the looks of things?

**Comment by Adammatthiesen** [comment]
> Yay! Thanks @Adammatthiesen — exciting to see this released.
> 
> I think this should actually go in the “Community plugins” section instead of the “tools and integrations” section given this is actually a Starlight plugin by the looks of things?

I put it in the same category as `starlight-blog` since it has almost the same functions just using different data as well as I had to make some tweaks to handle some things ghost does differently.

**Comment by delucis** [comment]
> I put it in the same category as `starlight-blog` since it has almost the same functions just using different data as well as I had to make some tweaks to handle some things ghost does differently.

Ah yeah, I think that will move up too now! Until the v0.19 release it was technically not a plugin.

**Comment by delucis** [comment]
Ah hang on a sec. We forgot to merge https://github.com/withastro/starlight/pull/1528

I’ll do that now, you can update branch and then move it!

**Comment by Adammatthiesen** [comment]
Updated.  lol when i first saw you message i was so confused.  glad it got cleared up!

**Pull request merged**
