### PR TITLE
i18n(fr): update `guides/overriding-components.md`

### PR DESCRIPTION
**Pull request by HiDeoo**
#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

This pull request update the french version of the `guides/overriding-components.md` page with the changes of #1168.

### CODE REVIEW

**Comment by vasfvitor** [comment]
According to [i18n tracker source change history](https://github.com/withastro/starlight/commits/main/docs/src/content/docs/guides/overriding-components.md?since=2023-10-11T13:25:42.000Z) there are two changes, but one is already in `SocialLinks` -> `SocialIcons` and the other is this current PR, with that being said, LGTM! and thank you!

**Comment by HiDeoo** [comment]
> According to [i18n tracker source change history](https://github.com/withastro/starlight/commits/main/docs/src/content/docs/guides/overriding-components.md?since=2023-10-11T13:25:42.000Z) there are two changes, but one is already in `SocialLinks` -> `SocialIcons` and the other is this current PR, with that being said, LGTM! and thank you! btw you are awesome

Thanks :heart: Yeah, this issue has been brought up before, I don't quite remember the exact reason but I think this may be a time query issue with GitHub or something similar making the GitHub UI shows the extra commit even though it shouldn't be there.

**Review by dreyfus92 — APPROVED** [review]
ÇMSB ✅

**Review by delucis — APPROVED** [review]
Didn't expect so little when switching to the "files changed" tab 😄 

For the record, you could totally have merged this yourself without waiting for my review 😅

**Comment by HiDeoo** [comment]
> Didn't expect so little when switching to the "files changed" tab 😄
> 
> For the record, you could totally have merged this yourself without waiting for my review 😅

Oh boy, I'm sorry, I think this was my initial intention, but I guess I totally forgot about it in the flow of other translations ^^

**Pull request merged**
