### PR TITLE
i18n(fr): update `reference/frontmatter.md`

### PR DESCRIPTION
**Pull request by HiDeoo**
#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

This PR updates `reference/frontmatter.md` in french with the missing translations for #516.

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Comment by HiDeoo** [comment]
Updated the pull request with the translations for #647 which was released in-between and to avoid losing track of the changes in the i18n tracker if this was merged as-is.

**Review by dreyfus92 — APPROVED** [review]
Superb, LGTM ✅

**Comment by HiDeoo** [comment]
Thanks for the double review 🙌

**Pull request merged**
