### PR TITLE
i18n(fr): add `reference/icons`

### PR DESCRIPTION
**Pull request by HiDeoo**
#### Description

This PR adds the French version of the `reference/icons` page with the changes from #2121.

### CODE REVIEW

**Review by delucis — APPROVED** [review]
Looks great! Noting that we’ve never added a `copiedLabel` prop to `<IconsList />` for translations so it always shows “Copied!”

Could be something to add in the future.

**Comment by HiDeoo** [comment]
> Looks great! Noting that we’ve never added a `copiedLabel` prop to `<IconsList />` for translations so it always shows “Copied!”
> 
> Could be something to add in the future.

Technically, we could now also use `Astro.locals.t('expressiveCode.copyButtonCopied')` but it's not available in a lot of languages I think.

**Comment by delucis** [comment]
> Technically, we could now also use `Astro.locals.t('expressiveCode.copyButtonCopied')` but it's not available in a lot of languages I think.

Yeah that’s true. Also for these one-off components I think I actually prefer the prop approach because then you are prompted to translate it in the same place as the translated content. Annoying for a component that gets repeated many times, but if only used once like this or the theme editor, then I think considering part of the “content” makes sense I think.

**Review by thomasbnt — APPROVED** [review]
Good!

**Pull request merged**
