### PR TITLE
Feat: Add sidebar state persistence

### PR DESCRIPTION
**Pull request by kitschpatrol**
#### Description

- Closes #971
- Sidebar now persists its scroll position and expanded / contracted section state across page navigations. It also scrolls the active sidebar item into view if necessary.

Builds on an initial implementation by @duncanwerner.

I grabbed the most salient bits of the issue thread below:

#### Feature criteria

- Respect the default "collapsed" state of the sidebar specified by SidebarItem config on first page navigations.
- Retain user's sidebar scroll position across page navigations.
- Retain user's sidebar sub-section detail expand / collapsed states across page navigations.
- Expand all ancestor detail elements of the active item (regardless of user's sidebar state changes).
- Ensure that the active item is visible after a page navigation (regardless of user's sidebar state changes).
- No Flash of Un-Scrolled Content (FLOUSC).

#### Possible improvements

- [ ] Track the initial expand / collapse state (from SidebarItem config) on first load before sessionStorage is set, and then apply this as the default if users don't actively change expand / collapse state of sections. (For example, the page is defined with all sections collapsed, the user navigates through several sections using the "next" buttons, this would collapse sections in the sidebar behind them once they're out of that section.)
- [ ] Maybe consider an intersection observer instead `getBoundingClientRect()` to determine if scrolling the sidebar is necessary. (Note that trusting `scrollIntoView()` on its own without checking bounds first can result in unnecessary scrolling.)
- [ ] Allow some padding when auto-scrolling a sidebar item into view. Currently, the sidebar scrolls the minimum amount necessary, leaving the item right on the edge of the scroll area.

#### Still to do
- [ ] Check implications of possible [view transitions](https://github.com/withastro/starlight/pull/694) feature.
- [x] Check implications of possible [multiple sidebar](https://github.com/withastro/starlight/discussions/959) feature.
- [ ] Strip comments. (I left these in to clarify any discussion around the PR, I assume we'll want to strip these since inline scripts aren't processed.)
- [ ] Verify that JS used meets [browserlist criteria](https://browsersl.ist/#q=%3E+0.5%25%2C+not+dead%2C+Chrome+%3E%3D+88%2C+Edge+%3E%3D+88%2C+Firefox+%3E%3D+98%2C+Safari+%3E%3D+15.4%2C+iOS+%3E%3D+15.4%2C+not+op_mini+all).

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Hey @kitschpatrol! Sorry for the _extremely_ long wait for a response here. Are you still interested in working on this PR or would you like me to take over? Looking into this functionality now and would have some feedback/suggestions if you’re interested!

**Comment by kitschpatrol** [comment]
Hey! No worries on the delay. I'm happy to work on it and of course would want any and all feedback and suggestions — but unfortunately time-wise I would have to delay picking it back up for a few weeks (Feb 26th), so no issues at all if you would rather take it over and get it released more quickly. 👍

**Comment by delucis** [comment]
Thanks — good to know! In that case, I’ll try to at least leave a round of feedback out of politeness, and if I have the chance before you do to address that, I’ll be happy to jump in 🙌

**Comment by kitschpatrol** [comment]
Hey @delucis, I'm back online. 👋

Happy to dig back into this PR if you have bandwidth for feedback.

**Comment by bdenham** [comment]
@delucis, @kitschpatrol: I'd love to see this get merged soon if it's ready. I added the fix to one of my sites and had to override several files 😅:
- Sidebar.astro
- SidebarSublist.astro
- navigation.ts
- schemas/badge.ts
- schemas/prevNextLink.ts
- schemas/sidebar.ts
- createPathFormatter.ts
- format-path.ts
- i18n.ts
- path.ts
- routing.ts
- slug.ts
- base.ts
- validateLogoImports.ts

Let me know if I can help. Thanks.

**Comment by kitschpatrol** [comment]
Hi @bdenham, yes I'm definitely standing by to respond to any feedback from the maintainers to keep this moving! (I think they're having a [busy week](https://twitter.com/astrodotbuild/status/1767294849848582202). 😅)

And hmm can you give any more info on all the overrides you said you needed? I just merged up this PR with `main` and it seems to still be [working fine](https://starlight-q5bbbpdsq-astrodotbuild.vercel.app/getting-started/) without additional changes / overrides?

**Comment by bdenham** [comment]
No, your PR is fine. I'm referring to what you need to do right now, outside the Starlight codebase. That is, when you're just using the Starlight integration in your site. The dependencies stack up when you need to override the sidebar to add the change you're committing to the sidebar. :)

**Comment by delucis** [comment]
Thanks again for this PR and your patience on this feature. In the end we realised there were quite a few additional considerations that meant we wanted to do this differently, so ended up implementing a separate approach in #2150. Nevertheless, appreciate you getting the ball rolling! The new feature will be available in v0.26 releasing later today 🚀

**Pull request closed without merging**
