### PR TITLE
Include basic anchor links for headings

### PR DESCRIPTION
**Pull request by at-the-vr**
#### Description

- Closes #1239  
- Returns Anchor links in form of `Underlines`

- Latest Results
image

### CODE REVIEW

**Comment by at-the-vr** [comment]
Hey Hideoo, following your [Blog Post](https://hideoo.dev/notes/starlight-heading-links) I am running into these build errors. How should I proceed to resolve them?

**Comment by HiDeoo** [comment]
> Hey Hideoo, following your [Blog Post](https://hideoo.dev/notes/starlight-heading-links) I am running into these build errors. How should I proceed to resolve them?

This is a docs specific issue, when https://github.com/withastro/starlight/pull/1256 is merged, this would be resolved (locally you can apply the same fix or temporarily remove the file having error).

Note that following the post I linked in #1239 may not be the best approach as this was written from the point of view of someone outside of Starlight adding the feature but when trying the same approach from inside Starlight, some parts become irrelevant/missing, e.g. the extra CSS file as we have direct access to Starlight CSS, no i18n, no way to be disabled, etc.

**Comment by at-the-vr** [comment]
Yeah I am just starting out, I do want to refer to Chris's PR for resolving mentioned issues (extra CSS/no i18n and more)

**Comment by HiDeoo** [comment]
Ah, I see the approach, amazing 👍 

> edit: the build issue has been resolved with #1256 fix 👍

Neat, thanks for the follow up.

**Comment by at-the-vr** [comment]
I would like to know the procedure to recreate [rehype-autolink.ts](https://github.com/withastro/docs/blob/main/plugins/rehype-autolink.ts) for starlight.
I tried `./packages/starlight/utils`for `rehype-autolink.ts` but following are the errors at present:
- `html-escaper` dependency not found
- Astro Docs specific modules `UILanguageKeys` from `../src/i18n/translation-checkers`, `useTranslationsForLang` from `../src/i18n/util` && `getLanguageCodeFromPathname, mdFilePathToUrl` from `./remark-fallback-lang` don't exist for starlight

That being said I believe I have to scrap off the current changes as they are not preferred.

**Comment by at-the-vr** [comment]
Bumping the Draft, I have to 

> I would like to know the procedure to recreate [rehype-autolink.ts](https://github.com/withastro/docs/blob/main/plugins/rehype-autolink.ts) for starlight. I tried `./packages/starlight/utils`for `rehype-autolink.ts` but following are the errors at present:
> 
> * `html-escaper` dependency not found
> * Astro Docs specific modules `UILanguageKeys` from `../src/i18n/translation-checkers`, `useTranslationsForLang` from `../src/i18n/util` && `getLanguageCodeFromPathname, mdFilePathToUrl` from `./remark-fallback-lang` don't exist for starlight
> 
> That being said I believe I have to scrap off the current changes as they are not preferred.

bumping the draft

**Comment by at-the-vr** [comment]
Closing this draft to avoid further staleness

**Pull request closed without merging**
