### PR TITLE
i18n(ko-KR): update `site-search.mdx`

### PR DESCRIPTION
**Pull request by jsparkdev**
#### Description

- update `site-search.mdx`
- #2009

### CODE REVIEW

**Comment by liruifengv** [comment]
Hi @jsparkdev There seems to be some formatting issues here. Can you fix it?

**Comment by jsparkdev** [comment]
Can you tell me what the problem is? 
I didn't find any problem...

**Comment by liruifengv** [comment]
> Can you tell me what the problem is? I didn't find any problem...

image
image

As you can see in the picture above, I don't know if formatting CI will automatically fix it or not.

**Comment by jsparkdev** [comment]
Thanks for the good point! What I see in my editor and what I see in production seem to be different :)

**Review by delucis — APPROVED** [review]
Thanks @jsparkdev and @liruifengv for the review 🚀

**Pull request merged**
