### PR TITLE
Adding VRCFR Creator to showcase

### PR DESCRIPTION
**Pull request by Ranily57**
#### What kind of changes does this PR include?

- Changes or translations of Starlight docs site content

#### Description

- What does this PR change? Just adding my website to your showcase
- Did you change something visual? Not at all, just adding a card on showcase.mdx

Link to the website: https://dev.vrchatfrance.fr

### CODE REVIEW

**Review by HiDeoo — COMMENTED** [review]
Great addition, thanks a lot for this!

Would you be able to update the thumbnail image to be `800 × 450` and match the dimensions of the other thumbnails in the showcase?

**Review by delucis — COMMENTED** [review]
Thanks for this @Ranily57! Would you mind reverting the changes in 78f36a3891e4e80aa9220? Normally we only update the English pages and leave changes to the translations to our translators, who have the best context on all the content for each page.

**Comment by Ranily57** [comment]
Okay i didn't see it was moved on a compoment, so i update it !

**Review by HiDeoo — APPROVED** [review]
> Okay i didn't see it was moved on a compoment, so i update it !

Thanks a lot and no worries at all, we merged the new component earlier today so a long time after your PR was opened.

I took the liberty to update the image by one kindly provided by Chris as it looks like the previous one lost its original ratio when resized but this now looks ready to me.

Thanks again for your contribution :raised_hands:

**Comment by Ranily57** [comment]
Thank's to you to allow us to use your system ! i hope to see the next update !

**Review by delucis — APPROVED** [review]
Nice work team, thanks both of you!

**Pull request merged**
