### PR TITLE
i18n(zh-tw): add Traditional Chinese UI translations

### PR DESCRIPTION
**Pull request by mingjunlu**
#### Description

- Adds Traditional Chinese UI translations

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for opening this PR @mingjunlu! I noticed you marked it as a draft. Let me know when it's ready for review 🙌

**Comment by liruifengv** [comment]
Thanks for add this. @mingjunlu 

Could you also add a changeset to this PR? You should be able to use the “Click here if you're a maintainer who wants to add a changeset to this PR” link in the Changeset comment or run pnpm changeset to use the CLI locally.

**Comment by mingjunlu** [comment]
@liruifengv Sure, changeset added.

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks! @mingjunlu

**Review by delucis — APPROVED** [review]
Thanks for the contribution @mingjunlu! And thanks for reviewing @liruifengv 💖

**Pull request merged**
