### PR TITLE
Add a generator meta tag with Starlight version info

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

- Adds a generator meta tag declaring that a site was built with Starlight to the HTML output as suggested by @rviscomi:

   ```html
   <meta name="generator" content="Starlight v0.1.1"/>
   ```

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]

**Comment by ElianCodes** [comment]
@delucis Wouldn't it make sense to add the Astro version somewhere in there? Maybe you've considered it and there's a reason why you didn't; in that case, ignore this and LGTM! 🥳

**Comment by delucis** [comment]
We already have the `Astro.generator` in there! This adds the Starlight one in addition.

New output looks like:

```html
<meta name="generator" content="Astro v2.5.7"/>
<meta name="generator" content="Starlight v0.1.1"/>
```

**Comment by ElianCodes** [comment]
Right! I completely overlooked that 🤦‍♂️

**Review by Yan-Thomas — APPROVED** [review]
LGTM!

**Pull request merged**
