### PR TITLE
docs: update showcase-sites.astro

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
**Description**

- Adds [LaunchFast](https://www.launchfa.st) to the Showcase Section
- Adds Capgo.app to the Showcase Section

### CODE REVIEW

**Review by apatel369 — APPROVED** [review]
Verified that cards are rendered correctly with correct link and image.

**Review by delucis — CHANGES_REQUESTED** [review]
Thanks @rishi-raj-jain! Can you resize the screenshots to match the dimensions described in our contributing guide?

https://github.com/withastro/starlight/blob/main/CONTRIBUTING.md#showcase

**Review by delucis — CHANGES_REQUESTED** [review]
Hmm, if I’m not mistaken, these screenshots are **1600x900px**, i.e. twice the size expected. Here are my steps for producing screenshots usually in case it helps:

1. Take a screenshot of the site using a browser resized to **1280×720px**. The responsive view in dev tools can be helpful for this.

2. Resize the screenshot to **800×450px** and make sure it is saved as a PNG. An online tool like [Squoosh](https://squoosh.app/) can help here.

**Comment by rishi-raj-jain** [comment]
Interesting! this is still at 1600*900. Let me do the update later today.

**Comment by delucis** [comment]
> Interesting! this is still at 1600*900. Let me do the update later today. Even though I resized the browser during the screenshot.

Yeah, probably due to the screen resolution. On high resolution (aka “retina”) displays, there is actually more than one device pixel for every 1 “web pixel” and screenshots include all of these.

**Comment by delucis** [comment]
@rishi-raj-jain I just updated branch for this PR to pull in changes from #2573 — that PR added a programmatic check for the image dimensions, so we should get easier confirmation if the screenshots are the right size or not!

**Comment by rishi-raj-jain** [comment]
@delucis Should be all good now.

**Review by delucis — APPROVED** [review]
Woo, looks good! Thanks for putting up with the fussy dimensions. I’m happy we got to test out the new test too so I have more confidence about these PRs when reviewing them 🙌

**Comment by rishi-raj-jain** [comment]
Appreciate your patience as well.

**Pull request merged**
