### PR TITLE
i18n(pt-PT): add "environmental-impact" page

### PR DESCRIPTION
**Pull request by rgilsimoes**
#### Description

- Add new /docs/pt-pt/environmental-impact page in Portuguese (Portugal)

### CODE REVIEW

**Review by delucis — CHANGES_REQUESTED** [review]
Looks great — thank you @rgilsimoes!

Could you also add a `pt-PT` translation for the sidebar link here, please?

https://github.com/withastro/starlight/blob/235149d05987bf6ecc5c9769f44c5c3b83d04ed8/docs/astro.config.mjs#L138

The English text is “Environmental Impact”.

**Review by Fryuni — APPROVED** [review]
LGTM! Thanks @rgilsimoes!

One tip though, we use squash merges and discard the commit messages, so you don't need to keep your own branch with super clean commits.

When you force-push GitHub discards in-progress reviews, including the review markers of what was already looked over, so even if you do want to rebase, organize, and rename your commits it is better to do that after the review iterations.

**Comment by rgilsimoes** [comment]
Thank you for the tip. I was not aware of that.

**Review by delucis — APPROVED** [review]
Thanks again @rgilsimoes — and for reviewing @Fryuni 🙌

**Pull request merged**
